# docker-compose.yml

version: '3.8'

services:
  reverse-importer:
    container_name: reverse-importer
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
